apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../development

patches:
  - path: deployment.values
    target:
      kind: Deployment
      name: alertmanager-teams-forwarder